# Site settings
title: Lauren Hoehn Velasco
email: laurenhoehnvelasco@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Lauren Hoehn Velasco is a graduate student of Economics at Boston College.
  She is an applied microeconomist with a primary interest in
  health, labor, and applied econometrics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://laurenhoehnvelasco.com" # the base hostname & protocol for your site
keep_files: ['/images', '/assets']

# Build settings
markdown: kramdown

collections:
  - research_papers
