# Site settings
title: Lauren Hoehn Velasco
email: hoehnl@bc.com
description: > # this means to ignore newlines until "baseurl:"
  Lauren Hoehn Velasco is a graduate student of Economics at Boston College.
  She is an applied microeconomist with a primary interest in development economics.
  Her reseach focuses on health and household dynamics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://laurenhoehnvelasco.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
