# Site settings
title: lauren hoehn velasco
email: lauren.hoehn@bc.edu
description: > # this means to ignore newlines until "baseurl:"
  Lauren Hoehn Velasco is a graduate student of Economics at Boston College.
  She is an applied microeconomist with a primary interest in development economics.
  Her reseach focuses on health and household dynamics.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://laurenhoehnvelasco.com" # the base hostname & protocol for your site
keep_files: ['/images']

# Build settings
markdown: kramdown
